// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifurbtuwhlshufowjcyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdXJidHV3aGxzaHVmb3dqY3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTEwMzUsImV4cCI6MjA2NDY4NzAzNX0.UnjiUSSDMk6_vBszYrpWS2_cD0h2kb51wU3-wooL6KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);